#!/bin/bash

source egan/bin/activate
#rm -r **/*.pyc
#rm celeba.pickle
rm latestlog
filename=runlog_$(date +"%Y%m%d-%H:%M:%S")
touch "$filename"
ln -s "$filename" latestlog
python -u train_egan_celeba.py $@ 2>&1 | tee "$filename"
